### ISSUE TITLE
Chromatic Transitions

### ISSUE THREAD

**Issue by lukeflowers** [hotgluebanjo/reuleaux#3]
Is there a way to add some feathering on the achromatic axis to not end up with halos in softer transitions from chromatic through achromatic? For example using power/gamma as a way to saturate can easily create those halos close to achromatic

**Comment by hotgluebanjo** [comment]
This briefly covered [here](https://github.com/hotgluebanjo/reuleaux/blob/master/doc/overview.md#smoothness). You can use [this](https://gist.github.com/hotgluebanjo/d9cd2228da7f480b23579155c812fc9e) simple tool as a drop-in replacement for the model if you don't need much control. Or you can manually do declination separate from distance in Cylindrical/Spherical Coordinates (for darker chroma in the resulting image like the Reuleaux default).

**Comment by lukeflowers** [comment]
Makes sense! Thanks for the response!

Thanks!
Luke Flowers
________________________________

**Comment by hotgluebanjo** [comment]
Closing this since it's an issue inherent to the design. Feel free to reopen if you have any issues.
