### ISSUE TITLE
Reuleaux User has continuity problems with Red Hue and Red Sat adjustments

### ISSUE THREAD

**Issue by thatcherfreeman** [hotgluebanjo/reuleaux#4]
I got the Reuleaux User Standalone DCTL and I noticed that if I shift the red hues and also change red saturation, there's a continuity issue. The color arrived at from the Magenta to Red direction does not align with the color from the Green to Red direction. None of the other colors are affected it seems. The same is true when the Red Hue slider is paired with an adjustment to Red Value.

<img width="1661" alt="image" src="https://github.com/hotgluebanjo/reuleaux/assets/21159194/8249bc5d-55e2-4912-add0-40d2ee1fa872">

<img width="1673" alt="image" src="https://github.com/hotgluebanjo/reuleaux/assets/21159194/3f1bf516-b1a5-4c90-a90f-29f0a399209a">

**Comment by thatcherfreeman** [comment]
[circles0000.exr.zip](https://github.com/hotgluebanjo/reuleaux/files/14154459/circles0000.exr.zip)

Here's the input image so you can test it.

**Comment by hotgluebanjo** [comment]
Thanks! Should be fixed. Let me know if it's not; couldn't check thoroughly in Fusion.

![image](https://github.com/hotgluebanjo/reuleaux/assets/66244111/6abfb2ca-f284-4cd1-b848-03bc2f8ee994)

Everything there is C0 and very janky. Probably better to test with Yuksel's splines or similar. Couldn't get his working sadly.
